// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbdlqwrtswpobinsppug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZGxxd3J0c3dwb2JpbnNwcHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjE4NzIsImV4cCI6MjA2NDgzNzg3Mn0.np5WRWIX2tpMEvmuVyMKLrzuY0VcZbiulEaLehDWYro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);